create table if not exists shipments (
  id uuid primary key default gen_random_uuid(),
  shipment_id text,
  load_id text,
  date date,
  month text,
  year text,
  carrier_name text,
  mode_of_transport text,
  product_type text,
  origin_country text,
  origin_region text,
  origin_state text,
  origin_city text,
  origin_zipcode text,
  origin_area text,
  destination_country text,
  destination_region text,
  destination_state text,
  destination_city text,
  destination_zipcode text,
  destination_area text,
  distance_km numeric,
  total_weight_kg numeric,
  transit_time_days numeric,
  operational_status text,
  shipment_cost_usd numeric,
  shipment_planned text,
  equipment text,
  equipment_weight_capacity_kg numeric,
  equipment_volume_capacity_m3 numeric,
  total_volume_shipment_m3 numeric,
  tendered_status text,
  estimated_delivery_date date,
  actual_delivery_date date,
  delays numeric,
  on_time_status text,
  shipment_order_type text,
  route text,
  created_at timestamp with time zone default now()
);
